version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swe30003
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/swe30003
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=FH575ZjakYbed9wl+kE1xn9wXWy4FmaLtup6H2zDzSk=
      - NODE_ENV=production
      - GOOGLE_CLIENT_ID=21664746739-c7t5f2kasvqq30d2k7e0dppg896fggo6.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - AUTH_TRUST_HOST=true
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
